{ pkgs, lib, config, ... }:
with lib;

let
  cfg = config.dpad.hyprpaper;
in
{
  options.dpad.hyprpaper = {
    enable = mkEnableOption (lib.mdDoc "Enable wallpaper service");

    wallpaper = mkOption {
      type = types.path;
      default = ./wallpaper.jpg;
    };
  };

  config = mkIf cfg.enable {
    home.packages = [
      pkgs.hyprpaper
    ];

    xdg.configFile."hypr/hyprpaper.conf" = {
      text = ''
        # Generated by Home Manager
        preload = ${cfg.wallpaper}
        wallpaper = ,${cfg.wallpaper}
        splash = false
      '';
    };
  };
}